### ISSUE TITLE
Error 1146 Table 'mysql.tmp_user_sys' doesn't exist' on query

### ISSUE THREAD

**Issue by alexanderfefelov** [alexanderfefelov/docker-mariadb-replication#2]
`show slave status \G`:

```
*************************** 1. row ***************************
                Slave_IO_State: Waiting for master to send event
                   Master_Host: mariadb-main-master.backpack.test
                   Master_User: replicator_yae4egie8eex
                   Master_Port: 3310
                 Connect_Retry: 60
               Master_Log_File: log-bin.000003
           Read_Master_Log_Pos: 340
                Relay_Log_File: relay-bin.000002
                 Relay_Log_Pos: 3619
         Relay_Master_Log_File: log-bin.000001
              Slave_IO_Running: Yes
             Slave_SQL_Running: No
               Replicate_Do_DB:
           Replicate_Ignore_DB:
            Replicate_Do_Table:
        Replicate_Ignore_Table:
       Replicate_Wild_Do_Table:
   Replicate_Wild_Ignore_Table:
                    Last_Errno: 1146
                    Last_Error: Error 'Table 'mysql.tmp_user_sys' doesn't exist' on query. Default database: 'mysql'. Query: 'INSERT INTO global_priv SELECT * FROM tmp_user_sys WHERE 0 <> @need_sys_user_creation;'
                  Skip_Counter: 0
           Exec_Master_Log_Pos: 3322
               Relay_Log_Space: 6679086
               Until_Condition: None
                Until_Log_File:
                 Until_Log_Pos: 0
            Master_SSL_Allowed: No
            Master_SSL_CA_File:
            Master_SSL_CA_Path:
               Master_SSL_Cert:
             Master_SSL_Cipher:
                Master_SSL_Key:
         Seconds_Behind_Master: NULL
 Master_SSL_Verify_Server_Cert: No
                 Last_IO_Errno: 0
                 Last_IO_Error:
                Last_SQL_Errno: 1146
                Last_SQL_Error: Error 'Table 'mysql.tmp_user_sys' doesn't exist' on query. Default database: 'mysql'. Query: 'INSERT INTO global_priv SELECT * FROM tmp_user_sys WHERE 0 <> @need_sys_user_creation;'
   Replicate_Ignore_Server_Ids:
              Master_Server_Id: 11
                Master_SSL_Crl:
            Master_SSL_Crlpath:
                    Using_Gtid: No
                   Gtid_IO_Pos:
       Replicate_Do_Domain_Ids:
   Replicate_Ignore_Domain_Ids:
                 Parallel_Mode: optimistic
                     SQL_Delay: 0
           SQL_Remaining_Delay: NULL
       Slave_SQL_Running_State:
              Slave_DDL_Groups: 0
Slave_Non_Transactional_Groups: 3
    Slave_Transactional_Groups: 0
```
